name: docker

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # push: true
          tags: well-known-components/template-server:latest
          # build-args: |
          #   arg1=value1
          #   arg2=value2
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


# QUAY
      # - uses: actions/checkout@v2
      # - name: Build Image
      #   id: build-image
      #   uses: redhat-actions/buildah-build@v2
      #   with:
      #     image: IMAGENAME
      #     tags: ${{ github.sha }} next
      #     dockerfiles: |
      #       ./Dockerfile

      # # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
      # # in which case 'username' and 'password' can be omitted.
      # - name: Push To quay.io
      #   id: push-to-quay
      #   uses: redhat-actions/push-to-registry@v2
      #   with:
      #     image: ${{ steps.build-image.outputs.image }}
      #     tags: ${{ steps.build-image.outputs.tags }}
      #     registry: quay.io/decentraland
      #     username: ${{ secrets.QUAY_USERNAME }}
      #     password: ${{ secrets.QUAY_TOKEN }}

      # - name: Print image url
      #   run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
